# SPDX-FileCopyrightText: openmod-tracker contributors
#
# SPDX-License-Identifier: CC0-1.0

default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [
          "--exclude-file=pixi.lock",
          "--skip=static/*",
          "--skip=example_data/*",
          "--ignore-words-list=doubleClick"
        ]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check for debugger imports and py37+ breakpoint() calls
      - id: debug-statements
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: check-illegal-windows-names
      - id: check-added-large-files
        args: [--enforce-all, --maxkb=100000]
      - id: trailing-whitespace
        exclude: "(example_data|static)/.*$"
      - id: end-of-file-fixer
        exclude: "^(example_data|static)/.*$"


ci: # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: monthly
