# SPDX-FileCopyrightText: 2026 Bryn Pickering <bp325@cam.ac.uk>
#
# SPDX-License-Identifier: MIT

[workspace]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "sankey-diagram-workshop"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=3.0.0,<4"
python = ">=3.14.2,<3.15"
numpy = ">=2.4.1,<3"
floweaver = ">=2.0.0,<3"
ipysankeywidget = ">=0.5.0,<0.6"
plotly = ">=6.5.2,<7"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"
ruff = ">=0.14.14,<0.15"
pre-commit = ">=4.5.1,<5"
